version: "3"

networks:
  postgresdb:
    external: false

services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=quicksoft
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=invoice_management
    networks:
      - postgresdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
    - "5432:5432"